### ISSUE TITLE
Service restart with delay

### ISSUE THREAD

**Issue by cmekki** [stegenfeldt/Atea.Windows#2]
when service restart a delay of X seconds/minutes before service start, powershell for dynamic change.

**Comment by stegenfeldt** [comment]
Adding an additional recovery task should work that you can enable should work. 
Perhaps a powershell script with a "sleep" as it would keep the powershell process active, with a parameter to tweak for the wait time.

**Comment by stegenfeldt** [comment]
Should be good to test in management group by now.
[Atea.Windows.Service.Monitoring.zip](https://github.com/stegenfeldt/Atea.Windows/files/539304/Atea.Windows.Service.Monitoring.zip)

**Comment by stegenfeldt** [comment]
[Atea.Windows.Service.Monitoring.zip](https://github.com/stegenfeldt/Atea.Windows/files/539376/Atea.Windows.Service.Monitoring.zip)

Updated MP is linked. Already imported in your management group, @cmekki. ;)
